### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by wouterfennis** [wouterfennis/fennisverhuur#1]
- [ ] Design finetune
- [ ] Foto's regelen
- [ ] Content regelen
- [ ] kleuren palette nalopen
- [ ] Eventueel logo designen
- [ ] Contactformulier herschrijven
- [ ] Website volledig testen 
- [ ] Hosting overzetten en testen
